edit ci/cd pipe

diff --git a/.github/workflows/Predeploy.yml b/.github/workflows/Predeploy.yml
--- a/.github/workflows/Predeploy.yml
+++ b/.github/workflows/Predeploy.yml
@@ -27,6 +27,26 @@ jobs:
           echo "JWT_AUDIENCE=InventoAngularClient" >> .env
           echo "FRONTEND_URL=http://localhost:4200" >> .env
 
+      - name: Restore and Build
+        run: |
+          dotnet restore 
+          dotnet build --configuration Release
+
+      - name: Test Docker Compose Up
+        run: |
+          docker compose up -d db redis api
+          echo "Waiting for services to stabilize..."
+          sleep 30
+          docker ps
+          if [ $(docker ps -f status=exited -q | wc -l) -gt 0 ]; then
+            echo "Error: One or more containers failed!"
+            docker compose logs
+            exit 1
+          fi
+
+      - name: Shutdown Test Environment
+        run: docker compose down
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -52,19 +72,3 @@ jobs:
           tags: |
             ${{ secrets.DOCKER_USERNAME }}/invento-frontend:latest
             ${{ secrets.DOCKER_USERNAME }}/invento-frontend:${{ github.sha }}
-
-      # 2. اختبار الـ Containers (Smoke Test) قبل الفركش
-      - name: Test Docker Compose Up
-        run: |
-          docker compose up -d db redis api
-          echo "Waiting for services to stabilize..."
-          sleep 30
-          docker ps
-          if [ $(docker ps -f status=exited -q | wc -l) -gt 0 ]; then
-            echo "Error: One or more containers failed!"
-            docker compose logs
-            exit 1
-          fi
-
-      - name: Shutdown Test Environment
-        run: docker compose down
